# Generated by Django 4.2.7 on 2025-08-16 01:28

import apps.administracion.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(choices=[(2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)])),
                ('trimestre', models.CharField(blank=True, choices=[('T1', 'Primer Trimestre'), ('T2', 'Segundo Trimestre'), ('T3', 'Tercer Trimestre'), ('T4', 'Cuarto Trimestre')], max_length=2, null=True)),
                ('archivo', models.FileField(help_text='Solo se permiten archivos PDF', upload_to=apps.administracion.models.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('titulo_personalizado', models.CharField(blank=True, help_text='Título personalizado para el documento', max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamaño_archivo', models.IntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-año', '-trimestre', 'tipo_documento__orden'],
            },
        ),
        migrations.CreateModel(
            name='Ley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ley',
                'verbose_name_plural': 'Leyes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('periodicidad', models.CharField(choices=[('ANUAL', 'Anual'), ('TRIMESTRAL', 'Trimestral')], max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('ley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subarticulos', to='administracion.ley')),
            ],
            options={
                'verbose_name': 'Sub-Artículo',
                'verbose_name_plural': 'Sub-Artículos',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('ley', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('subarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='administracion.subarticulo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('subarticulo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('tipo_acceso', models.CharField(choices=[('VISUALIZACION', 'Visualización'), ('DESCARGA', 'Descarga')], max_length=20)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acceso', to='administracion.documento')),
            ],
            options={
                'verbose_name': 'Log de Acceso',
                'verbose_name_plural': 'Logs de Acceso',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='administracion.tipodocumento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario_subida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('tipo_documento', 'año', 'trimestre')},
        ),
    ]
